export const DATA = [
  {
    id: 1,
    title: "learn_more",
    description: "learn_more_description",
    linkText: "find_out",
    image: "/images/learn-more.jpg",
    backgroundColor: "bg-blue-1",
    buttonColor: "bg-orange-1",
    items: [
      {
        id: 1,
        title: "what_girl_scouts_do",
        description: "what_girl_scouts_do_description",
        image: "/images/learn-1.jpeg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-1",
        linkText: "learn_more",
      },
      {
        id: 2,
        title: "ways_to_participate",
        description: "ways_to_participate_description",
        image: "/images/learn-2.jpg",
        shape: "sqr-arch",
        buttonColor: "bg-blue-2",
        linkText: "learn_more",
      },
      {
        id: 3,
        title: "grade_levels",
        description: "grade_levels_description",
        image: "/images/learn-3.jpg",
        shape: "sqr-circle",
        buttonColor: "bg-purple-3",
        linkText: "learn_more",
      },
      {
        id: 4,
        title: "girl_scout_uniforms",
        description: "girl_scout_uniforms_description",
        image: "/images/learn-4.jpeg",
        shape: "sqr-arch",
        buttonColor: "bg-orange-4",
        linkText: "learn_more",
      },
      {
        id: 5,
        title: "badge_explorer",
        description: "badge_explorer_description",
        image: "/images/learn-5.jpg",
        shape: "sqr-circle",
        buttonColor: "bg-purple-1",
        linkText: "learn_more",
      },
      {
        id: 6,
        title: "diversity_equity_inclusion",
        description: "diversity_equity_inclusion_description",
        image: "/images/learn-6.png",
        shape: "sqr-octagon",
        buttonColor: "bg-purple-3",
        linkText: "learn_more",
      },
    ],
  },
  {
    id: 2,
    title: "join",
    description: "join_description",
    linkText: "join_now",
    image: "/images/join.png",
    backgroundColor: "bg-brown-1",
    buttonColor: "bg-purple-3",
    items: [
      {
        id: 1,
        title: "troop_catalog",
        description: "troop_catalog_description",
        image: "/images/join-1.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-1",
        linkText: "join_a_troop",
      },
      {
        id: 2,
        title: "go_solo",
        description: "go_solo_description",
        image: "/images/join-2.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-2",
        linkText: "get_involved",
      },
      {
        id: 3,
        title: "learn_more",
        description: "join_learn_more_description",
        image: "/images/join-3.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-3",
        linkText: "get_involved",
      },
    ]
  },
  {
    id: 3,
    title: "events",
    description: 'events_description',
    image: "/images/events.jpg",
    linkText: "search_now",
    backgroundColor: "bg-green-2",
    buttonColor: "bg-purple-1",
    items: [
      {
        id: 1,
        title: "dl_events",
        description: "dl_events_description",
        image: "/images/event-1.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-2",
        linkText: "find_events",
      },
      {
        id: 3,
        title: "gsle_events",
        description: "gsle_events_description",
        image: "/images/event-2.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-purple-2",
        linkText: "find_events",
      },
    ]
  },
  {
    id: 4,
    title: "family_engagement",
    description: "family_description",
    linkText: "get_started",
    image: "/images/family.jpg",
    backgroundColor: "bg-purple-3",
    buttonColor: "bg-orange-2",
    items: [
      {
        id: 1,
        title: "raising_awesome_girls",
        description: "raising_awesome_girls_description",
        image: "/images/fam-1.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-1",
        linkText: "learn_more",
      },
      {
        id: 2,
        title: "the_family_experience",
        description: "the_family_experience_description",
        image: "/images/fam-2.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-purle-2",
        linkText: "learn_more",
      },
      {
        id: 3,
        title: "family_fun_day",
        description: "family_fun_day_description",
        image: "/images/fam-3.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-green-1",
        linkText: "learn_more",
      },
      {
        id: 4,
        title: "drop_in_programs",
        description: "drop_in_programs_description",
        image: "/images/fam-4.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-yellow-1",
        linkText: "learn_more",
      },
      {
        id: 5,
        title: "newsroom",
        description: "newsroom_description",
        image: "/images/fam-5.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-2",
        linkText: "learn_more",
      },
    ]
  },
  {
    id: 5,
    title: "volunteer",
    description: "volunteer_description",
    linkText: "get_connected",
    image: "/images/volunteer.jpg",
    backgroundColor: "bg-yellow-1",
    buttonColor: "bg-blue-1",
    items: [
      {
        id: 1,
        title: "become_a_volunteer",
        description: "become_a_volunteer_description",
        image: "/images/vol-1.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-1",
        linkText: "get_started",
      },
      {
        id: 2,
        title: "start_your_own_troop",
        description: "start_your_own_troop_description",
        image: "/images/vol-2.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-purple-2",
        linkText: "get_started",
      },
      {
        id: 3,
        title: "program_and_events",
        description: "program_and_events_description",
        image: "/images/vol-3.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-3",
        linkText: "get_started",
      },
      {
        id: 4,
        title: "volunteer_essentials",
        description: "volunteer_essentials_description",
        image: "/images/vol-3.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-3",
        linkText: "learn_more",
      },
      {
        id: 5,
        title: "troop_planner",
        description: "troop_planner_description",
        image: "/images/vol-3.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-3",
        linkText: "learn_more",
      },
      {
        id: 6,
        title: "learn_more",
        description: "volunteer_learn_more_description",
        image: "/images/thumb-2.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-6",
        linkText: "get_started",
      },
    ]
  },
  {
    id: 6,
    title: "support",
    description: "support_description",
    linkText: "support_girls",
    image: "/images/support.jpg",
    backgroundColor: "bg-orange-1",
    buttonColor: "bg-purple-2",
    items: [
      {
        id: 1,
        title: "donate",
        description: "donate_description",
        image: "/images/support-1.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-1",
        linkText: "learn_more",
      },
      {
        id: 2,
        title: "fundraising_events",
        description: "fundraising_events_description",
        image: "/images/support-1.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-1",
        linkText: "learn_more",
      },
      {
        id: 3,
        title: "alum_re_engagement",
        description: "alum_re_engagement_description",
        image: "/images/support-3.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-3",
        linkText: "learn_more",
      },
      {
        id: 4,
        title: "partners",
        description: "partners_description",
        image: "/images/support-4.jpg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-4",
        linkText: "learn_more",
      },
    ]
  },
  {
    id: 7,
    title: "reservations",
    description: "reservations_description",
    linkText: "learn_more",
    image: "/images/reservations.jpg",
    backgroundColor: "bg-purple-1",
    buttonColor: "bg-green-4",
    items: [
      {
        id: 3,
        title: "explore_reservable_space",
        description: "explore_reservable_space_description",
        image: "/images/res-2.jpeg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-2",
        linkText: "learn_more",
      },
      {
        id: 2,
        title: "check_availability",
        description: "check_availability_description",
        image: "/images/res-2.jpeg",
        shape: "sqr-octagon",
        buttonColor: "bg-orange-2",
        linkText: "learn_more",
      },
    ]
  }
];
